#!/usr/bin/env python3
"""
Génère des fichiers .tfvars dynamiquement depuis un inventaire JSON.
Utile quand les valeurs viennent d'une API externe ou d'un état Azure/K8s.

Usage:
    python terraform_tfvars_generator.py --input inventory.json --output prod.tfvars
    python terraform_tfvars_generator.py --input inventory.json --output prod.tfvars --dry-run
    python terraform_tfvars_generator.py --input inventory.json --output prod.tfvars --env-override
"""

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from typing import Dict, Any, Optional

# Jinja2 est optionnel — on détecte sa présence à l'import.
# try/except à l'import est le pattern standard pour les dépendances optionnelles.
# Si jinja2 n'est pas installé, HAS_JINJA2=False → on utilise un fallback simple.
try:
    from jinja2 import Environment, FileSystemLoader, BaseLoader, StrictUndefined
    HAS_JINJA2 = True
except ImportError:
    HAS_JINJA2 = False

logger = logging.getLogger(__name__)

# Template Jinja2 par défaut intégré dans le script.
# Les délimiteurs {%- et -%} suppriment les espaces/sauts de ligne autour des blocs.
# Cela évite les lignes vides dans le fichier .tfvars généré.
#
# Filtres Jinja2 utilisés :
# - | lower  : convertit True/False Python → true/false Terraform (HCL)
# - | tojson : sérialise un dict Python → JSON compatible HCL
DEFAULT_TEMPLATE = """\
# Generated by terraform_tfvars_generator.py — do not edit manually
# Source: {{ _source }}

{% for key, value in variables.items() -%}
{% if value is string -%}
{{ key }} = "{{ value }}"
{% elif value is boolean -%}
{{ key }} = {{ value | lower }}
{% elif value is mapping -%}
{{ key }} = {{ value | tojson }}
{% else -%}
{{ key }} = {{ value }}
{% endif %}
{%- endfor %}
"""


def load_inventory(filepath: str) -> Dict[str, Any]:
    """
    Charge les variables depuis un fichier JSON.
    Le JSON peut contenir n'importe quel type compatible HCL :
    strings, nombres, booleans, objets (maps), listes.
    """
    with open(filepath) as f:
        return json.load(f)


def enrich_with_env(variables: Dict[str, Any], prefix: str = "TF_VAR_") -> Dict[str, Any]:
    """
    Surcharge les variables avec les variables d'environnement préfixées TF_VAR_.

    COHÉRENCE AVEC TERRAFORM :
    Terraform reconnaît nativement les variables d'env TF_VAR_<name>.
    On utilise la même convention pour être compatible :
    - TF_VAR_region=eastus     → terraform voit region="eastus"
    - ce script voit aussi region="eastus" → le tfvars généré est cohérent

    UTILITÉ EN CI/CD :
    Les secrets CI (tokens, passwords) sont stockés dans des secrets GitHub/Azure.
    Le runner les injecte comme variables d'env → ce script les récupère sans les écrire
    dans des fichiers (ce qui serait risqué pour la sécurité).

    Priorité : les env vars ÉCRASENT les valeurs du fichier JSON.
    C'est voulu : les overrides CI ont toujours priorité sur les fichiers versionés.
    """
    for key, value in os.environ.items():
        if key.startswith(prefix):
            # "TF_VAR_REGION" → "region" (on normalise en minuscules)
            # len(prefix) = 7 pour "TF_VAR_" → on slicé depuis l'index 7
            var_name = key[len(prefix):].lower()
            variables[var_name] = value
            logger.debug(f"Override '{var_name}' from env var {key}")
    return variables


def render_tfvars(
    variables: Dict[str, Any],
    source: str,
    template_path: Optional[str] = None,
) -> str:
    """
    Rend le template Jinja2 ou génère le contenu manuellement si jinja2 est absent.

    DEUX CAS :
    1. Sans Jinja2 (HAS_JINJA2=False) :
       Fallback simple avec isinstance() pour gérer les types HCL.
       Limité aux templates plats (pas de boucles, conditions, filtres).

    2. Avec Jinja2 :
       a. template_path fourni → charger le fichier template de l'utilisateur
          FileSystemLoader : cherche le template dans le dossier parent du fichier
       b. template_path non fourni → utiliser DEFAULT_TEMPLATE intégré
          BaseLoader + from_string() : compiler un template depuis une string Python

    StrictUndefined dans tous les cas :
    → Erreur explicite si le template référence une variable absente du contexte.
    → Évite les "" silencieuses dans le .tfvars produit.
    """
    if not HAS_JINJA2:
        # Fallback sans jinja2 — supporte str, bool, et les types JSON simples
        lines = [f"# Generated from {source}", ""]
        for key, value in variables.items():
            if isinstance(value, str):
                lines.append(f'{key} = "{value}"')
            elif isinstance(value, bool):
                # str(True) = "True", str(False) = "False"
                # Terraform attend "true"/"false" → .lower() est obligatoire
                lines.append(f'{key} = {str(value).lower()}')
            else:
                # json.dumps() sérialise nombres, listes, dicts en JSON
                # Le JSON est syntaxiquement compatible avec HCL pour les types simples
                lines.append(f'{key} = {json.dumps(value)}')
        return "\n".join(lines)

    if template_path:
        # FileSystemLoader : le répertoire du template permet {% include %} relatifs
        template_dir = str(Path(template_path).parent)
        env = Environment(loader=FileSystemLoader(template_dir), undefined=StrictUndefined)
        template = env.get_template(Path(template_path).name)
    else:
        # BaseLoader + from_string : compile une string comme template sans accès au filesystem
        env = Environment(loader=BaseLoader(), undefined=StrictUndefined)
        template = env.from_string(DEFAULT_TEMPLATE)

    # render() injecte les variables dans le template
    # _source est un nom de convention (préfixe _) pour les variables "internes" au template
    return template.render(variables=variables, _source=source)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Terraform .tfvars Generator")
    parser.add_argument("--input", "-i", required=True, help="Inventaire JSON source")
    parser.add_argument("--output", "-o", required=True, help="Fichier .tfvars de sortie")
    parser.add_argument("--template", help="Template Jinja2 custom (optionnel)")
    parser.add_argument(
        "--env-override", action="store_true",
        help="Prendre en compte les TF_VAR_* de l'environnement (priorité sur JSON)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Afficher sans écrire")
    parser.add_argument("--log-level", default="INFO", choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    return parser


def main(args=None) -> int:
    parser = build_parser()
    parsed = parser.parse_args(args)
    logging.basicConfig(level=parsed.log_level, format="%(asctime)s [%(levelname)s] %(message)s")

    try:
        variables = load_inventory(parsed.input)
        logger.info(f"Loaded {len(variables)} variable(s) from {parsed.input}")

        if parsed.env_override:
            # Modifier en place ou réassigner — enrich_with_env retourne le dict modifié
            variables = enrich_with_env(variables)

        content = render_tfvars(variables, source=parsed.input, template_path=parsed.template)

        if parsed.dry_run:
            # --dry-run : afficher sur stdout pour inspection avant d'écrire
            print(content)
            return 0

        with open(parsed.output, "w") as f:
            f.write(content)
        logger.info(f"Written to {parsed.output}")
        return 0

    except FileNotFoundError as e:
        logger.error(f"File not found: {e}")
        return 1
    except Exception as e:
        logger.error(f"Error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
