apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-gateway-fabric-to-myapp
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: myapp
  policyTypes:
    - Ingress
  ingress:
    - from:
        # NGINX Gateway Fabric provisions the data-plane (nginx) Deployment
        # in the same namespace as the Gateway (nginx-gateway).
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nginx-gateway
      ports:
        - protocol: TCP
          port: 5000
