apiVersion: v1
kind: ServiceAccount
metadata:
  name: kv-reader-sa
  namespace: workload-identity-demo
  annotations:
    azure.workload.identity/client-id: "${WORKLOAD_IDENTITY_CLIENT_ID}"
  labels:
    azure.workload.identity/use: "true"
