# Default values for myapp.
replicaCount: 1

image:
  repository: umairlabacr.azurecr.io/myapp
  pullPolicy: Always
  tag: "7"

service:
  type: ClusterIP
  port: 5000

containerPort: 5000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  enabled: false

httpRoute:
  enabled: false
